# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Add repository
      run: "sudo dpkg --add-architecture i386 && sudo apt update"
      
    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: wget gdebi-core libgl1-mesa-glx:i386
        version: "@latest"
        
    - name: Download Steam
      run: wget -O ~/steam.deb http://media.steampowered.com/client/installer/steam.deb
      
    - name: Install Steam
      run: sudo gdebi ~/steam.deb

    - name: Run Steam
      run: steam
